package Formulario;
import javax.swing.JOptionPane;

//Bibliotecas para a tabela
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.Color;
import java.awt.Component;


public class frmIRPF extends javax.swing.JFrame {

    /**
     * Creates new form frmIRPF
     */
    public frmIRPF() {
        initComponents();
        setLocationRelativeTo(this);
        
        jPanelDep.setVisible(false);
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupo = new javax.swing.ButtonGroup();
        jPanelPrincipal = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxtSalarioBruto = new javax.swing.JTextField();
        jBCalcularImposto = new javax.swing.JButton();
        jBLimpar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanelDep = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxDep = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTxtDeducao = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTxtSalarioLiquido = new javax.swing.JTextField();
        jTxtImposto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRBAdicionarDep = new javax.swing.JRadioButton();
        jRBtnNaoAdicionarDep = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAliquotas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Imposto de Renda");
        setResizable(false);

        jPanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logoIF.png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(41, 153, 41));
        jLabel8.setText("IMPOSTO DE RENDA PESSOA FÍSICA");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Valor do Salário Bruto:");

        jTxtSalarioBruto.setBackground(new java.awt.Color(225, 255, 225));

        jBCalcularImposto.setBackground(new java.awt.Color(30, 121, 30));
        jBCalcularImposto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBCalcularImposto.setForeground(new java.awt.Color(255, 255, 255));
        jBCalcularImposto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calculadora.png"))); // NOI18N
        jBCalcularImposto.setText("Calcular IRPF");
        jBCalcularImposto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularImpostoActionPerformed(evt);
            }
        });

        jBLimpar.setBackground(new java.awt.Color(255, 0, 0));
        jBLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBLimpar.setForeground(new java.awt.Color(255, 255, 255));
        jBLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/borrachabranca.png"))); // NOI18N
        jBLimpar.setText("Limpar");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Valor do Salário Líquido:");

        jPanelDep.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Selecione a quantidade de dependentes:");

        jComboBoxDep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "até 3 filhos", "4 ou mais filhos" }));
        jComboBoxDep.setSelectedIndex(-1);
        jComboBoxDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDepActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Dedução:");

        jTxtDeducao.setEnabled(false);

        javax.swing.GroupLayout jPanelDepLayout = new javax.swing.GroupLayout(jPanelDep);
        jPanelDep.setLayout(jPanelDepLayout);
        jPanelDepLayout.setHorizontalGroup(
            jPanelDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDepLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanelDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDepLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxDep, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDepLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtDeducao, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPanelDepLayout.setVerticalGroup(
            jPanelDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtDeducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Valor do Imposto:");

        jTxtSalarioLiquido.setBackground(new java.awt.Color(225, 255, 225));
        jTxtSalarioLiquido.setText("R$");
        jTxtSalarioLiquido.setToolTipText("");
        jTxtSalarioLiquido.setEnabled(false);

        jTxtImposto.setBackground(new java.awt.Color(225, 255, 225));
        jTxtImposto.setText("R$");
        jTxtImposto.setToolTipText("");
        jTxtImposto.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Deseja adicionar dependentes?");

        jRBAdicionarDep.setBackground(new java.awt.Color(255, 255, 255));
        btnGrupo.add(jRBAdicionarDep);
        jRBAdicionarDep.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRBAdicionarDep.setText("Sim");
        jRBAdicionarDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBAdicionarDepActionPerformed(evt);
            }
        });

        jRBtnNaoAdicionarDep.setBackground(new java.awt.Color(255, 255, 255));
        btnGrupo.add(jRBtnNaoAdicionarDep);
        jRBtnNaoAdicionarDep.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRBtnNaoAdicionarDep.setText("Não");
        jRBtnNaoAdicionarDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtnNaoAdicionarDepActionPerformed(evt);
            }
        });

        jTableAliquotas.setBackground(new java.awt.Color(225, 255, 225));
        jTableAliquotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Faixa de Salário", "Alíquota(%)", "Dedução"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAliquotas);
        if (jTableAliquotas.getColumnModel().getColumnCount() > 0) {
            jTableAliquotas.getColumnModel().getColumn(0).setPreferredWidth(135);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Faixas de Alíquotas:");

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(125, 125, 125))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(191, 191, 191)))
                            .addGap(118, 118, 118)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jBCalcularImposto, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTxtImposto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtSalarioLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(13, 13, 13)
                            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                    .addComponent(jRBAdicionarDep)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRBtnNaoAdicionarDep))
                                .addComponent(jTxtSalarioBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanelDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(44, 44, 44))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(28, 28, 28)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTxtSalarioBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRBAdicionarDep)
                    .addComponent(jRBtnNaoAdicionarDep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtImposto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtSalarioLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(26, 26, 26)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCalcularImposto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCalcularImpostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularImpostoActionPerformed
        calcularImposto();
    }//GEN-LAST:event_jBCalcularImpostoActionPerformed

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        limparDados();
    }//GEN-LAST:event_jBLimparActionPerformed

    private void jRBAdicionarDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBAdicionarDepActionPerformed
        jPanelDep.setVisible(true);
    }//GEN-LAST:event_jRBAdicionarDepActionPerformed

    private void jRBtnNaoAdicionarDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtnNaoAdicionarDepActionPerformed
        jPanelDep.setVisible(false);
        jComboBoxDep.setSelectedIndex(-1);
    }//GEN-LAST:event_jRBtnNaoAdicionarDepActionPerformed

    private void jComboBoxDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDepActionPerformed
        if (jComboBoxDep.getSelectedIndex() == -1) {
            return;
        }
        
        String opcao = (String) jComboBoxDep.getSelectedItem();
        switch (opcao) {
            case "selecione":
                jTxtDeducao.setText("");
            break;
            case "até 3 filhos":
                jTxtDeducao.setText("5%");
                break;
            case "4 ou mais filhos":
                jTxtDeducao.setText("10%");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jComboBoxDepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmIRPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmIRPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmIRPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIRPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmIRPF().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrupo;
    private javax.swing.JButton jBCalcularImposto;
    private javax.swing.JButton jBLimpar;
    private javax.swing.JComboBox jComboBoxDep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelDep;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JRadioButton jRBAdicionarDep;
    private javax.swing.JRadioButton jRBtnNaoAdicionarDep;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAliquotas;
    private javax.swing.JTextField jTxtDeducao;
    private javax.swing.JTextField jTxtImposto;
    private javax.swing.JTextField jTxtSalarioBruto;
    private javax.swing.JTextField jTxtSalarioLiquido;
    // End of variables declaration//GEN-END:variables

    
    public void calcularImposto(){
        try{
            String salBruto = jTxtSalarioBruto.getText();
            
            if(salBruto.isEmpty()){
                JOptionPane.showMessageDialog(null,"Preencha o campo com o valor do salário bruto!", "Questão 02",JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            double salarioBruto = Double.parseDouble(salBruto), imposto, salarioLiquido, deducao, deducaoDep = 0;
            
            if(salarioBruto < 0){
                JOptionPane.showMessageDialog(null,"Insira um valor válido para o salário bruto!\nNão são permitidos valores negativos, tente novamente.", "Questão 02",JOptionPane.WARNING_MESSAGE);
                limparDados();
                return;
            }
            
            if(jRBAdicionarDep.isSelected()){
                if (jComboBoxDep.getSelectedIndex() == -1) {
                    JOptionPane.showMessageDialog(null,"Campo vazio!\nSelecione uma opção de dependentes.","Questão 02",JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
                String opcao = (String) jComboBoxDep.getSelectedItem();
                switch (opcao) {
                    case "até 3 filhos":
                        deducaoDep = 0.05;
                        break;
                    case "4 ou mais filhos":
                        deducaoDep = 0.1;
                        break;
                    default:
                        break;
                }
                
            }else if(jRBtnNaoAdicionarDep.isSelected()){
                deducaoDep = 0;
                
            }else{
                JOptionPane.showMessageDialog(null,"Campo vazio!\nSelecione uma opção válida e tente novamente.","Questão 02",JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            
            if(salarioBruto <= 2259.20){
                
                imposto = 0;
                salarioLiquido = salarioBruto;
                
            }else if(salarioBruto <= 2826.65){
                
                deducao = 169.44;
                imposto = (salarioBruto - (salarioBruto*deducaoDep)) * 0.075 - deducao;
                salarioLiquido = salarioBruto - imposto;
                
            }else if(salarioBruto <= 3751.05){
                
                deducao = 381.44;
                imposto = (salarioBruto - (salarioBruto*deducaoDep)) * 0.15 - deducao;
                salarioLiquido = salarioBruto - imposto;
                
            }else if(salarioBruto <= 4664.68){
                
                deducao = 662.77;
                imposto = (salarioBruto - (salarioBruto*deducaoDep)) * 0.225 - deducao;
                salarioLiquido = salarioBruto - imposto;
                
            }else {
                
                deducao = 896;
                imposto = (salarioBruto - (salarioBruto*deducaoDep)) * 0.275 - deducao;
                salarioLiquido = salarioBruto - imposto;
                
            }
            
            destacarFaixa(jTableAliquotas,salarioBruto);
            
            jTxtImposto.setText(String.format("R$ %.2f",imposto));
            jTxtSalarioLiquido.setText(String.format("R$ %.2f",salarioLiquido));
            
        }catch(NumberFormatException n){
            JOptionPane.showMessageDialog(null,"O valor do salário bruto está incorreto!\nDigite apenas números válidos no campo.","Questão 02",JOptionPane.ERROR_MESSAGE);
            limparDados();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erro inesperado!","Questão 02",JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    public void limparDados(){
        jTxtSalarioBruto.setText("");
        jTxtSalarioLiquido.setText("R$");
        jTxtImposto.setText("R$");
        jPanelDep.setVisible(false);
        jComboBoxDep.setSelectedIndex(-1);
        jTxtDeducao.setText("");
        btnGrupo.clearSelection();
        
        jTableAliquotas.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component comp = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                comp.setBackground(new Color(225,255,225));

                return comp;
            }
        });
        jTableAliquotas.repaint();
        
    }
    
    public void preencherTabela(){
        DefaultTableModel tabela = (DefaultTableModel) jTableAliquotas.getModel();
        
        Object[][] dados = {
            {"Até R$2.259,00", "-","-"},
            {"R$2.259,21 a R$2.826,65", "7,5%","R$169,44"},
            {"R$2.826,66 a R$3.751,05", "15%", "R$381,44"},
            {"R$3.751,06 a R$4.664,68", "22,5%","R$662,77"},
            {"Acima de 4.664,68", "27,5%","R$896,00"}
        };
        
        for (Object[] linha : dados) {
            tabela.addRow(linha);
        }
    }
    
    public void destacarFaixa(JTable tabela, double salarioBruto) {
        tabela.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component comp = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                comp.setBackground(new Color(225,255,225));
                if (salarioBruto <= 2259.20 && row == 0) {
                    comp.setBackground(new Color(30, 121, 30));        
                } else if (salarioBruto > 2259.20 && salarioBruto <= 2826.65 && row == 1) {
                    comp.setBackground(new Color(30, 121, 30)); 
                } else if (salarioBruto > 2826.65 && salarioBruto <= 3751.05 && row == 2) {
                    comp.setBackground(new Color(30, 121, 30));
                } else if (salarioBruto > 3751.05 && salarioBruto <= 4664.68 && row == 3) {
                    comp.setBackground(new Color(30, 121, 30));
                } else if (salarioBruto > 4664.68 && row == 4) {
                    comp.setBackground(new Color(30, 121, 30));
                }

                return comp;
            }
        });

        tabela.repaint();
    }
}
