package formulario;

import controller.ProdutoController;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produto;

public class TelaCRUD extends javax.swing.JFrame {
    
    private ProdutoController controller;
    
    public TelaCRUD() {
        initComponents();
        setLocationRelativeTo(this);
        
        controller = new ProdutoController();
        carregarProdutosComboBox();
        carregarProdutos();    
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelProduto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBtAdicionar = new javax.swing.JButton();
        jBtLimparAdicionar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jTxtPreco = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtDesc = new javax.swing.JTextArea();
        jTxtQtde = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBtEditar = new javax.swing.JButton();
        jBtLimparEditar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTxtNomeEditar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTxtPrecoEditar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTxtDescEditar = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jTxtQtdeEditar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxProdutos = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePesquisar = new javax.swing.JTable();
        jBtPesquisar = new javax.swing.JButton();
        jBtLimparPesquisar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jComboBoxFiltro = new javax.swing.JComboBox();
        jTxtValorPesquisa = new javax.swing.JTextField();
        Excluir = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jComboBoxOpcao = new javax.swing.JComboBox();
        jBtExcluir = new javax.swing.JButton();
        jTxtValorExcluir = new javax.swing.JTextField();
        jLabelExcluir = new javax.swing.JLabel();
        jBtLimparExcluir = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableExcluir = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD");
        setResizable(false);

        jPanelProduto.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo2Farmacia.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 122, 0));
        jLabel3.setText("Adicionar Produto");

        jBtAdicionar.setBackground(new java.awt.Color(0, 102, 0));
        jBtAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        jBtAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastrar.png"))); // NOI18N
        jBtAdicionar.setText("ADICIONAR");
        jBtAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAdicionarActionPerformed(evt);
            }
        });

        jBtLimparAdicionar.setBackground(new java.awt.Color(186, 3, 3));
        jBtLimparAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtLimparAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        jBtLimparAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/borrachabranca.png"))); // NOI18N
        jBtLimparAdicionar.setText("LIMPAR");
        jBtLimparAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtLimparAdicionarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Nome do Produto:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Preço do Produto:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Quantidade de Estoque:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Descrição do Produto:");

        jTxtNome.setBackground(new java.awt.Color(240, 255, 240));
        jTxtNome.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jTxtPreco.setBackground(new java.awt.Color(240, 255, 240));
        jTxtPreco.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jTxtDesc.setBackground(new java.awt.Color(240, 255, 240));
        jTxtDesc.setColumns(20);
        jTxtDesc.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTxtDesc.setRows(5);
        jScrollPane1.setViewportView(jTxtDesc);

        jTxtQtde.setBackground(new java.awt.Color(240, 255, 240));
        jTxtQtde.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanelProdutoLayout = new javax.swing.GroupLayout(jPanelProduto);
        jPanelProduto.setLayout(jPanelProdutoLayout);
        jPanelProdutoLayout.setHorizontalGroup(
            jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutoLayout.createSequentialGroup()
                .addGroup(jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProdutoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanelProdutoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelProdutoLayout.createSequentialGroup()
                                .addGroup(jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(49, 49, 49)
                                .addGroup(jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtPreco)
                                    .addComponent(jTxtNome)))
                            .addGroup(jPanelProdutoLayout.createSequentialGroup()
                                .addGroup(jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelProdutoLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jTxtQtde))))))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProdutoLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jBtAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jBtLimparAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanelProdutoLayout.setVerticalGroup(
            jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtLimparAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        jTabbedPane1.addTab("Adicionar", jPanelProduto);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo2Farmacia.jpg"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 122, 0));
        jLabel4.setText("Editar Produto");

        jBtEditar.setBackground(new java.awt.Color(0, 102, 0));
        jBtEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtEditar.setForeground(new java.awt.Color(255, 255, 255));
        jBtEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        jBtEditar.setText("SALVAR");
        jBtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtEditarActionPerformed(evt);
            }
        });

        jBtLimparEditar.setBackground(new java.awt.Color(186, 3, 3));
        jBtLimparEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtLimparEditar.setForeground(new java.awt.Color(255, 255, 255));
        jBtLimparEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/borrachabranca.png"))); // NOI18N
        jBtLimparEditar.setText("LIMPAR");
        jBtLimparEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtLimparEditarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Nome do Produto:");

        jTxtNomeEditar.setBackground(new java.awt.Color(240, 255, 240));
        jTxtNomeEditar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTxtNomeEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeEditarActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Preço do Produto:");

        jTxtPrecoEditar.setBackground(new java.awt.Color(240, 255, 240));
        jTxtPrecoEditar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Descrição do Produto:");

        jTxtDescEditar.setBackground(new java.awt.Color(240, 255, 240));
        jTxtDescEditar.setColumns(20);
        jTxtDescEditar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTxtDescEditar.setRows(5);
        jScrollPane3.setViewportView(jTxtDescEditar);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Quantidade de Estoque:");

        jTxtQtdeEditar.setBackground(new java.awt.Color(240, 255, 240));
        jTxtQtdeEditar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTxtQtdeEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtQtdeEditarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Selecione o produto que deseja editar:");

        jComboBoxProdutos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProdutosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jBtEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jBtLimparEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTxtNomeEditar)
                                    .addComponent(jTxtPrecoEditar)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                    .addComponent(jTxtQtdeEditar)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(26, 26, 26)
                                .addComponent(jComboBoxProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTxtNomeEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPrecoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTxtQtdeEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtLimparEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(jBtEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("Editar", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo2Farmacia.jpg"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 122, 0));
        jLabel11.setText("Pesquisar Produto");

        jTablePesquisar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Preço", "Descrição", "Qtde em Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTablePesquisar);
        if (jTablePesquisar.getColumnModel().getColumnCount() > 0) {
            jTablePesquisar.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        jBtPesquisar.setBackground(new java.awt.Color(0, 102, 0));
        jBtPesquisar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jBtPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa.png"))); // NOI18N
        jBtPesquisar.setText("PESQUISAR");
        jBtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesquisarActionPerformed(evt);
            }
        });

        jBtLimparPesquisar.setBackground(new java.awt.Color(186, 3, 3));
        jBtLimparPesquisar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtLimparPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jBtLimparPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/borrachabranca.png"))); // NOI18N
        jBtLimparPesquisar.setText("LIMPAR");
        jBtLimparPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtLimparPesquisarActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Tabela com os dados dos Produtos");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Selecione o que deseja filtrar:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Insira o valor que deseja pesquisar:");

        jComboBoxFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Nome" }));
        jComboBoxFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFiltroActionPerformed(evt);
            }
        });

        jTxtValorPesquisa.setBackground(new java.awt.Color(240, 255, 240));
        jTxtValorPesquisa.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtValorPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)
                                    .addComponent(jComboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtLimparPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtValorPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtLimparPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Pesquisar", jPanel3);

        Excluir.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 122, 0));
        jLabel12.setText("Excluir Produto");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo2Farmacia.jpg"))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Selecione um item:");

        jComboBoxOpcao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Nome" }));
        jComboBoxOpcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOpcaoActionPerformed(evt);
            }
        });

        jBtExcluir.setBackground(new java.awt.Color(0, 102, 0));
        jBtExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jBtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lixeira.png"))); // NOI18N
        jBtExcluir.setText("EXCLUIR");
        jBtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtExcluirActionPerformed(evt);
            }
        });

        jTxtValorExcluir.setBackground(new java.awt.Color(240, 255, 240));
        jTxtValorExcluir.setToolTipText("");

        jLabelExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelExcluir.setText("Insira o produto:");

        jBtLimparExcluir.setBackground(new java.awt.Color(186, 3, 3));
        jBtLimparExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtLimparExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jBtLimparExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/borrachabranca.png"))); // NOI18N
        jBtLimparExcluir.setText("LIMPAR");
        jBtLimparExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtLimparExcluirActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Tabela com os dados dos Produtos");

        jTableExcluir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Preço", "Descrição", "Qtde em Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableExcluir);
        if (jTableExcluir.getColumnModel().getColumnCount() > 0) {
            jTableExcluir.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        javax.swing.GroupLayout ExcluirLayout = new javax.swing.GroupLayout(Excluir);
        Excluir.setLayout(ExcluirLayout);
        ExcluirLayout.setHorizontalGroup(
            ExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExcluirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ExcluirLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(ExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExcluirLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ExcluirLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(ExcluirLayout.createSequentialGroup()
                        .addGroup(ExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtValorExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtLimparExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))))
        );
        ExcluirLayout.setVerticalGroup(
            ExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExcluirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ExcluirLayout.createSequentialGroup()
                        .addGroup(ExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ExcluirLayout.createSequentialGroup()
                                .addGroup(ExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(jLabelExcluir)
                        .addGap(7, 7, 7)
                        .addComponent(jTxtValorExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtLimparExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("Excluir", Excluir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAdicionarActionPerformed
        adicionarProduto();
    }//GEN-LAST:event_jBtAdicionarActionPerformed

    private void jBtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtEditarActionPerformed
        editarProduto();
    }//GEN-LAST:event_jBtEditarActionPerformed

    private void jTxtNomeEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeEditarActionPerformed

    private void jComboBoxProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProdutosActionPerformed
        if (jComboBoxProdutos.getSelectedIndex() == -1) {
            return;
        }
        
        preencherCampos();           
    }//GEN-LAST:event_jComboBoxProdutosActionPerformed

    private void jTxtQtdeEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtQtdeEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtQtdeEditarActionPerformed

    private void jBtLimparPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtLimparPesquisarActionPerformed
        limparPesquisar();
    }//GEN-LAST:event_jBtLimparPesquisarActionPerformed

    private void jBtLimparExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtLimparExcluirActionPerformed

        limparExcluir();
    }//GEN-LAST:event_jBtLimparExcluirActionPerformed

    private void jBtLimparAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtLimparAdicionarActionPerformed
        limparAdicionar();
    }//GEN-LAST:event_jBtLimparAdicionarActionPerformed

    private void jBtLimparEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtLimparEditarActionPerformed
        limparEditar();
    }//GEN-LAST:event_jBtLimparEditarActionPerformed

    private void jComboBoxFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFiltroActionPerformed

    }//GEN-LAST:event_jComboBoxFiltroActionPerformed

    private void jComboBoxOpcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOpcaoActionPerformed
        int opcao = jComboBoxOpcao.getSelectedIndex();
        
        if(opcao == 0){
            jLabelExcluir.setText("Insira o ID do produto:");
        }
        
        if(opcao == 1){
            jLabelExcluir.setText("Insira o nome do produto:");
        }
    }//GEN-LAST:event_jComboBoxOpcaoActionPerformed

    private void jBtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesquisarActionPerformed
        pesquisarProduto();
    }//GEN-LAST:event_jBtPesquisarActionPerformed

    private void jBtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtExcluirActionPerformed
        excluirProduto();
    }//GEN-LAST:event_jBtExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Excluir;
    private javax.swing.JButton jBtAdicionar;
    private javax.swing.JButton jBtEditar;
    private javax.swing.JButton jBtExcluir;
    private javax.swing.JButton jBtLimparAdicionar;
    private javax.swing.JButton jBtLimparEditar;
    private javax.swing.JButton jBtLimparExcluir;
    private javax.swing.JButton jBtLimparPesquisar;
    private javax.swing.JButton jBtPesquisar;
    private javax.swing.JComboBox jComboBoxFiltro;
    private javax.swing.JComboBox jComboBoxOpcao;
    private javax.swing.JComboBox jComboBoxProdutos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelExcluir;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelProduto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableExcluir;
    private javax.swing.JTable jTablePesquisar;
    private javax.swing.JTextArea jTxtDesc;
    private javax.swing.JTextArea jTxtDescEditar;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtNomeEditar;
    private javax.swing.JTextField jTxtPreco;
    private javax.swing.JTextField jTxtPrecoEditar;
    private javax.swing.JTextField jTxtQtde;
    private javax.swing.JTextField jTxtQtdeEditar;
    private javax.swing.JTextField jTxtValorExcluir;
    private javax.swing.JTextField jTxtValorPesquisa;
    // End of variables declaration//GEN-END:variables
    
    public void adicionarProduto(){
        try{
            
            if (jTxtNome.getText().isEmpty() || jTxtPreco.getText().isEmpty() || 
                jTxtDesc.getText().isEmpty() || jTxtQtde.getText().isEmpty()) {
    
                JOptionPane.showMessageDialog(null, "Preencha todos os campos corretamente!","Questão 01",JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            String nome = jTxtNome.getText();
            Double preco = Double.parseDouble(jTxtPreco.getText());
            String descricao = jTxtDesc.getText();
            int qtde = Integer.parseInt(jTxtQtde.getText());
            
            controller.adicionarProduto(nome, preco, descricao, qtde);
            limparAdicionar();
            carregarProdutos();
            carregarProdutosComboBox();
            
        }catch(NumberFormatException n){
            JOptionPane.showMessageDialog(null, "Dado inserido em formato incorreto!", "Questão 01", JOptionPane.ERROR_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro inesperado!", "Questão 01", JOptionPane.ERROR_MESSAGE);
            limparAdicionar();
        }
    }
    
    public void editarProduto(){
        try{
            if(jComboBoxProdutos.getSelectedItem() == null || jComboBoxProdutos.getSelectedIndex() == -1){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos corretamente!","Questão 01",JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            int id = controller.buscarIdPorNome((String) jComboBoxProdutos.getSelectedItem());
            
            String nome = jTxtNomeEditar.getText();
            Double preco = Double.parseDouble(jTxtPrecoEditar.getText());
            String descricao = jTxtDescEditar.getText();
            int qtde = Integer.parseInt(jTxtQtdeEditar.getText());
            
            controller.editarProduto(id, nome, preco, descricao, qtde);
            
            carregarProdutos();
            carregarProdutosComboBox();
            limparEditar();
            
            
        }catch(NumberFormatException n){
            JOptionPane.showMessageDialog(null, "Dado inserido em formato incorreto!", "Questão 01", JOptionPane.ERROR_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro inesperado!", "Questão 01", JOptionPane.ERROR_MESSAGE);
            limparAdicionar();
        }
    }
    
    public void pesquisarProduto() {
        try {
            if (jComboBoxFiltro.getSelectedItem() == null || jTxtValorPesquisa.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos corretamente!", "Questão 01", JOptionPane.WARNING_MESSAGE);
                return;
            }

            String item = (String) jComboBoxFiltro.getSelectedItem();
            String valor = jTxtValorPesquisa.getText();

            Produto produto = null;

            if (item.equals("ID")) {
                try {
                    int id = Integer.parseInt(valor); 
                    produto = controller.pesquisarProduto(id);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "O ID deve ser um número válido!", "Questão 01", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } else {
                int id = controller.buscarIdPorNome(valor);
                produto = controller.pesquisarProduto(id);
            }

            DefaultTableModel modelo = (DefaultTableModel) jTablePesquisar.getModel();
            modelo.setRowCount(0);

            if (produto != null) {
                modelo.addRow(new Object[]{
                    produto.getId(),
                    produto.getNome(),
                    produto.getPreco(),
                    produto.getDescricao(),
                    produto.getQtdeEstoque()
                });
            } else {
                JOptionPane.showMessageDialog(null, "Nenhum produto encontrado!", "Questão 01", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro inesperado!", "Questão 01", JOptionPane.ERROR_MESSAGE);
        }
    }


    
    public void excluirProduto(){
    try{
        if(jComboBoxOpcao.getSelectedItem() == null || jTxtValorExcluir.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos corretamente!","Questão 01",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String item = (String) jComboBoxOpcao.getSelectedItem();
        int id;
        
        if(item.equals("ID")){
            id = Integer.parseInt(jTxtValorExcluir.getText());
        } else {
            id = controller.buscarIdPorNome(jTxtValorExcluir.getText());
        }
        
        if (id == -1) {
            JOptionPane.showMessageDialog(null, "Produto não encontrado!", "Questão 01", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        controller.excluirProduto(id);
        
        carregarProdutos();
        carregarProdutosComboBox();
        limparExcluir();
        
    }catch(NumberFormatException n){
        JOptionPane.showMessageDialog(null, "Dado inserido em formato incorreto!", "Questão 01", JOptionPane.ERROR_MESSAGE);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erro inesperado!", "Questão 01", JOptionPane.ERROR_MESSAGE);
        limparExcluir();
    }
}
    
    public void preencherCampos() {
        String nomeProduto = (String) jComboBoxProdutos.getSelectedItem();
        Produto produto;

        int id = controller.buscarIdPorNome(nomeProduto);
        produto = controller.pesquisarProduto(id);

        if (produto != null) {
            jTxtNomeEditar.setText(produto.getNome());
            jTxtPrecoEditar.setText(String.valueOf(produto.getPreco()));
            jTxtDescEditar.setText(produto.getDescricao());
            jTxtQtdeEditar.setText(String.valueOf(produto.getQtdeEstoque()));
        } else {
            JOptionPane.showMessageDialog(null, "Produto não encontrado.", "Questão 01", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void carregarProdutosComboBox() {
        controller.carregarProdutosComboBox(jComboBoxProdutos);
    }

    
    public void carregarProdutos() {
        DefaultTableModel modelo = (DefaultTableModel) jTableExcluir.getModel();
        controller.carregarProdutosNaTabela(modelo);
    }
    
    public void limparAdicionar(){
        jTxtNome.setText("");
        jTxtPreco.setText("");
        jTxtDesc.setText("");
        jTxtQtde.setText("");
    }
    
    public void limparEditar(){
        jComboBoxProdutos.setSelectedIndex(-1);
        jTxtNomeEditar.setText("");
        jTxtPrecoEditar.setText("");
        jTxtDescEditar.setText("");
        jTxtQtdeEditar.setText("");
    }
    
    public void limparPesquisar(){
        jComboBoxFiltro.setSelectedIndex(-1);
        jTxtValorPesquisa.setText("");
        
        DefaultTableModel modelo = (DefaultTableModel) jTablePesquisar.getModel();
        modelo.setRowCount(0);
    }
    
    public void limparExcluir(){
        jComboBoxOpcao.setSelectedIndex(-1);
        jTxtValorExcluir.setText("");
        jLabelExcluir.setText("Insira o produto:");
    }
}
